# Create k8s context

  - name: Set context cluster 
    command: kubectl config set-cluster exo --server=https://{{ public_ip.ip_address }}:443 --insecure-skip-tls-verify=true
    tags: context

  - name: Set context user
    command: kubectl config set-credentials exo --username={{ k8s_username }} --password={{ k8s_password}}

  - name: Create context
    command: kubectl config set-context exo --cluster=exo --user=exo

  - name: Use context
    command: kubectl config use-context exo
